### ISSUE TITLE
Release File 

### ISSUE THREAD

**Issue by Sherviin** [eprints/eprints#435] opened 2016-11-24 12:32 UTC
Hi,
After updating the source.list I keep receiving the following error:
shervin@shervin-VirtualBox:~$ sudo apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Ign:4 http://deb.eprints.org stable/ InRelease                                
Get:5 http://archive.ubuntu.com/ubuntu xenial-security InRelease [102 kB]     
Ign:6 http://deb.eprints.org stable/ Release                                  
Ign:7 http://deb.eprints.org stable/ Packages.diff/Index                      
Ign:8 http://deb.eprints.org stable/ Translation-en_US
Ign:9 http://deb.eprints.org stable/ Translation-en                          
Ign:10 http://deb.eprints.org stable/ Packages                               
Ign:8 http://deb.eprints.org stable/ Translation-en_US                       
Ign:9 http://deb.eprints.org stable/ Translation-en                          
Ign:10 http://deb.eprints.org stable/ Packages       
Ign:8 http://deb.eprints.org stable/ Translation-en_US
Ign:9 http://deb.eprints.org stable/ Translation-en  
Ign:10 http://deb.eprints.org stable/ Packages       
Ign:8 http://deb.eprints.org stable/ Translation-en_US
Ign:9 http://deb.eprints.org stable/ Translation-en  
Hit:10 http://deb.eprints.org stable/ Packages       
Ign:8 http://deb.eprints.org stable/ Translation-en_US                         
Ign:9 http://deb.eprints.org stable/ Translation-en  
Ign:8 http://deb.eprints.org stable/ Translation-en_US
Ign:9 http://deb.eprints.org stable/ Translation-en
Fetched 306 kB in 2s (144 kB/s)
Reading package lists... Done
**W: The repository 'http://deb.eprints.org stable/ Release' does not have a Release file.**
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
shervin@shervin-VirtualBox:~$ sudo apt-get install eprints
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 eprints : PreDepends: apache2-mpm-prefork but it is not installable
E: Unable to correct problems, you have held broken packages.

Software Installer=>same result...

**Comment by jiadiyao** [comment] 2017-10-25 12:24
Dave has posted instructions on ep-tech mailling list on installing EPrints on Ubuntu 16, which removed the apache2-mpm-prefork package. I am pasting here hope it will be useful

Hi all,

There was some user group feedback from the Repository Fringe regarding
the "Enterprise Compliance" of EPrints, specifically for Ubuntu 16.04. 

I am keen on ensuring that the next release of EPrints 3.3 has a Debian
package that can be directly installed from the APT repository at
deb.eprints.org, without need for some interesting hacks, which have
been previously discussed.  At present I am aware of two issue with the
current EPrints 3.3.15 Debian package:

1. apache2-mpm-prefork no longer exists as a Debian package and causes
a failed dependency.  This can be worked around by creating a fake
Debian package for this.

2. If Apache is installed to use the MPM event module, this is known to
have issues which can cause Apache to experience a segmentation fault.
 After some investigation, I believe this is down to LibXSLT.so, which
is installed by the Debian package libxml-libxslt-perl, which is a
dependency of EPrints.  However, I have also found that I can manually
install and run EPrints quite happily without this package, including
successfully running the unit tests.

Based on this experience, I have created an modified version of the
EPrints 3.3.15 Debian package, which removed the apache2-mpm-prefork
dependency and replaces it with just an apache2 dependency and removes
the the libxml-libxslt-perl dependency altogether.  I have successfully
installed and run the unit tests for this on my own Ubuntu 16.04 server
with only two minor issues:

1. A deprecation warning for the use of '\C' in a regular expression
the escape_char function of URI/Escape.pm
 
2. Unit tests for SWORD fail.
 
However, both these issues have been fixed on GitHub (https://github.co
m/eprints/eprints/) since EPrints 3.3.15 was released.

It would be useful if others could test my modified Debian package to
see if they can find any other issues with it.  It is available at:

http://files.eprints.org/1712/

In particular:

1. Are there other situations where Apache will suffer a Segmentation
fault other than that caused by LibXSLT.so, which this Debian package
will no longer install.
 
2. Is the libxml-libxslt-perl package required for any core EPrints
functionality that has not been identified by running unit tests. (If
necessary, this library can be installed through CPAN rather than as a
Debian package and this way does not appear to cause a segmentation
fault).

I also intend to further test whether this modified EPrints 3.3.15
Debian package can successfully installed on Ubuntu 14.04, as it would
be preferable to have a single package for all currently supported
versions of Ubuntu.  Based on the changes: only removing a dependency
and effectively relaxing another dependency, I believe that any use of
this package as an upgrade on an existing EPrints install should behave
the same as using the original EPrints 3.3.15 Debian package.

Any feedback on this would be greatly appreciated.

Regards

David Newman
EPrints Services

**Closed by jiadiyao** 2017-10-25 12:24 UTC
