### ISSUE TITLE
Repository is not indexed by Google Scholar 

### ISSUE THREAD

**Issue by glen-lee** [eprints/eprints#529] opened 2024-01-08 09:40 UTC
Hi. We have a repository https://kc.umn.ac.id/ containing ~20k items, we're using Eprints 3.3.

However, our repository never gets indexed by Scholar. So far we have tried to:
1. Add sitemaps https://kc.umn.ac.id/sitemap.xml
2. Update Eprints URL format as suggested by https://github.com/eprints/eprints/issues/450
and waited for ~3 months with no result

Can someone help? I've sent Google Scholar Support an email but I don't know if they still reply to emails. Most of the links to contact Google Scholar Support are no longer valid as well.

Thanks and I apologize in advance if this issue doesn't belong here.

**Comment by drn05r** [comment] 2024-01-08 10:41
Duplicate of #450 (see replies there)

**Closed as completed by drn05r** 2024-01-08 10:41 UTC
